### ISSUE TITLE
Assert in JSC::JITMathIC<JSC::JITSubGenerator>::generateInline

### ISSUE THREAD

**Issue by vertexodessa** [Metrological/WebKitForWayland#158]
```
#13 0x7fcea3e8 in ?? ()
(gdb) bt
#0  0x756344b8 in WTFCrash () at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/Assertions.cpp:324
#1  0x73c3baa4 in JSC::JITMathIC<JSC::JITSubGenerator>::generateInline (this=<optimized out>, jit=..., state=..., shouldEmitProfiling=<optimized out>) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/jit/JITMathIC.h:89
#2  0x73c3ed1c in JSC::JIT::emitMathICFast<JSC::JITSubGenerator, long long (*)(JSC::ExecState*, long long, long long, JSC::ArithProfile*), long long (*)(JSC::ExecState*, long long, long long)> (this=0x7fce9e80, mathIC=0x575f9b60, currentInstruction=0x595e913c, profiledFunction=0x73c564e0 <JSC::operationValueSubProfiled(JSC::ExecState*, JSC::EncodedJSValue, JSC::EncodedJSValue, JSC::ArithProfile*)>, nonProfiledFunction=0x73c5642c <JSC::operationValueSub(JSC::ExecState*, JSC::EncodedJSValue, JSC::EncodedJSValue)>) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/jit/JITArithmetic.cpp:750
#3  0x73c381d4 in JSC::JIT::emit_op_sub (this=0x7fce9e80, currentInstruction=0x595e913c) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/jit/JITArithmetic.cpp:931
#4  0x73c2fc94 in JSC::JIT::privateCompileMainPass (this=0x7fce9e80) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/jit/JIT.cpp:328
#5  0x73c31b6c in JSC::JIT::compileWithoutLinking (this=0x7fce9e80, effort=JSC::JITCompilationCanFail) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/jit/JIT.cpp:613
#6  0x739493d4 in JSC::JITWorklist::Plan::compileInThread (this=0x7fce9e60) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/jit/JITWorklist.cpp:48
#7  0x7394b128 in JSC::JITWorklist::Plan::compileNow (codeBlock=<optimized out>) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/jit/JITWorklist.cpp:89
#8  0x739487a4 in JSC::JITWorklist::compileLater (this=0x6e7ee280, codeBlock=0x599a9f00) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/jit/JITWorklist.cpp:217
#9  0x73c98ac8 in JSC::LLInt::jitCompileAndSetHeuristics (codeBlock=0x599a9f00, exec=<optimized out>) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:339
#10 0x73c9597c in JSC::LLInt::entryOSR (exec=0x7fcea368, codeBlock=0x599a9f00, name=0x75c7b448 "entry_osr_function_for_construct", kind=JSC::LLInt::Prologue) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:361
#11 0x73c95cd0 in JSC::LLInt::llint_entry_osr_function_for_construct (exec=0x7fcea368, pc=<optimized out>) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:391
#12 0x7394d3c0 in llint_entry () from ./usr/lib/libWPEWebKit.so.0
#13 0x7fcea3e8 in ?? ()

```

**Comment by vertexodessa** [comment]
Occured during attempt to launch Youtube tv interface
https://www.youtube.com/tv

**Comment by albertd** [comment]
@vertexodessa is this issue still valid in wpe-2017 branch, if so please reopen.
