### ISSUE TITLE
Assertion failed in WebCore::AppendPipeline::AppendPipeline

### ISSUE THREAD

**Issue by vertexodessa** [Metrological/WebKitForWayland#159]
Happened during an attempt to play an MSE video on https://www.youtube.com/tv

```
#0  0x75588438 in WTFCrash () at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/Assertions.cpp:324
324         *(int *)(uintptr_t)0xbbadbeef = 0;
(gdb) bt
#0  0x75588438 in WTFCrash () at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/Assertions.cpp:324
#1  0x74cacc6c in WTF::adoptGRef<_GstElement> (ptr=0x87d040) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebCore/platform/graphics/gstreamer/GRefPtrGStreamer.cpp:30
#2  0x748af560 in WebCore::AppendPipeline::AppendPipeline (this=0x51765c30, mediaSourceClient=..., sourceBufferPrivate=..., playerPrivate=<optimized out>) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerMSE.cpp:1194
#3  0x748b5a24 in WebCore::MediaSourceClientGStreamerMSE::addSourceBuffer (this=0x51768000, sourceBufferPrivate=...) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerMSE.cpp:2251
#4  0x748ba5c8 in WebCore::MediaSourceGStreamer::addSourceBuffer (this=<optimized out>, contentType=..., sourceBufferPrivate=...) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebCore/platform/graphics/gstreamer/MediaSourceGStreamer.cpp:77
#5  0x7496a508 in WebCore::MediaSource::createSourceBufferPrivate (this=<optimized out>, type=..., ec=@0x7fd9bed0: 0) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebCore/Modules/mediasource/MediaSource.cpp:856
#6  0x7496b5e4 in WebCore::MediaSource::addSourceBuffer (this=0x523ca410, type=..., ec=@0x7fd9bed0: 0) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebCore/Modules/mediasource/MediaSource.cpp:537
#7  0x74e35898 in WebCore::jsMediaSourcePrototypeFunctionAddSourceBuffer (state=0x7fd9bf18) at DerivedSources/WebCore/JSMediaSource.cpp:322
warning: GDB can't find the start of the function at 0x5a6b35df.
#8  0x5a6b35e0 in ?? ()

```

**Comment by eocanha** [comment]
Thanks for reporting. Fixed by https://github.com/Metrological/WebKitForWayland/commit/7cdd403e717b4a102ffbbee7ce6e1dea65db2ddc on latest master.

**Comment by vertexodessa** [comment]
thanks @eocanha
