### ISSUE TITLE
Assertion failed in getStreamByAppsrc

### ISSUE THREAD

**Issue by vertexodessa** [Metrological/WebKitForWayland#160]
Happened during an attempt to play an MSE video on https://www.youtube.com/tv
 
```
Core was generated by `/usr/bin/WPEWebProcess 37 -1'.
Program terminated with signal SIGBUS, Bus error.
#0  0x756c6408 in WTFCrash () at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/Assertions.cpp:324
324         *(int *)(uintptr_t)0xbbadbeef = 0;
(gdb) bt
#0  0x756c6408 in WTFCrash () at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/Assertions.cpp:324
#1  0x74a04994 in WTF::DequeIteratorBase<_Stream*, 0u>::removeFromIteratorsList (this=<optimized out>) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/Deque.h:567
#2  0x74a04a98 in WTF::DequeIteratorBase<_Stream*, 0u>::~DequeIteratorBase (this=0x5612e998, __in_chrg=<optimized out>) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/Deque.h:628
#3  0x749ff330 in getStreamByAppsrc (source=0x87a0b8, appsrc=0xd8c468) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/Deque.h:158
#4  0x749ff664 in enabledAppsrcNeedData (appsrc=0xd8c468, userData=0x87a0b8) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebCore/platform/graphics/gstreamer/WebKitMediaSourceGStreamer.cpp:720
#5  0x7144a71c in gst_app_src_emit_need_data (appsrc=0xd8c468, size=4096) at gstappsrc.c:1033
#6  0x7144bc0c in gst_app_src_create (bsrc=0xd8c468, offset=<optimized out>, size=4096, buf=0x5612eb90) at gstappsrc.c:1182
#7  0x714041cc in gst_base_src_get_range (src=0xd8c468, offset=<optimized out>, length=4096, buf=buf@entry=0x5612eca0) at gstbasesrc.c:2445
#8  0x71406c1c in gst_base_src_loop (pad=0x6e410048) at gstbasesrc.c:2721
#9  0x71952f78 in gst_task_func (task=0x6e41c0d0) at gsttask.c:317
#10 0x71954808 in default_func (tdata=<optimized out>, pool=<optimized out>) at gsttaskpool.c:68
#11 0x71a5cc40 in g_thread_pool_thread_proxy (data=<optimized out>) at /usr/src/debug/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gthreadpool.c:307
#12 0x71a5bad0 in g_thread_proxy (data=0x4bbf50) at /usr/src/debug/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gthread.c:780
#13 0x727e8cdc in start_thread (arg=0x5612f360) at pthread_create.c:314
#14 0x725df6a0 in __thread_start () at ../ports/sysdeps/unix/sysv/linux/mips/clone.S:150

```

**Comment by eocanha** [comment]
Solved on https://github.com/Metrological/WebKitForWayland/commit/6565a41cfa2fa4fc32505762d68b40927da01aa2

It seems that Deque isn't the best data structure to be used when creating a lot of iterators from different threads.

**Comment by vertexodessa** [comment]
Thanks! I'm going to close the issue
