### ISSUE TITLE
wpe-20170728: stack-buffer-overflow @JSC::ConservativeRoots::genericAddSpan

### ISSUE THREAD

**Issue by dwrobel** [Metrological/WebKitForWayland#589]
- branch: wpe-20170728 (496e8ba676f7c47fff7135720fa37b69d24b7256)
- url: https://yt-dash-mse-test.commondatastorage.googleapis.com/unit-tests/2018.html?test_type=encryptedmedia-test&timestamp=1554377522685&tests=33,34&command=run
- compiled with: -fsanitize=address
- reproducibility 100%

```
==11821==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffff969bd8 at pc 0x7fa5963c4dc6 bp 0x7fffff967660 sp 0x7fffff967650
READ of size 8 at 0x7fffff969bd8 thread T0

Address 0x7fffff969bd8 is located in stack of thread T0 at offset 56 in frame
    #0 0x7fa591f810af in JSC::callWithCurrentThreadState(WTF::ScopedLambda<void (JSC::CurrentThreadState&)> const&) (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-1/_install/usr/lib/libWPEWebKit.so.0+0x7d870af)

  This frame has 2 object(s):
    [32, 56) 'state' <== Memory access at offset 56 overflows this variable
    [96, 136) 'state_registerState'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/home/dwrobel/projects/webkit/WebPlatformForEmbedded-1/_install/usr/lib/libWPEWebKit.so.0+0xc1cadc5) in void JSC::ConservativeRoots::genericAddSpan<JSC::CompositeMarkHook>(void*, void*, JSC::CompositeMarkHook&)
Shadow bytes around the buggy address:
  0x10007ff25320: f2 f2 00 00 00 00 00 f2 f2 f2 f2 f2 f2 f2 00 00
  0x10007ff25330: 00 00 00 00 00 00 00 f2 f2 f2 f2 f2 f2 f2 00 00
  0x10007ff25340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007ff25350: 00 00 f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00
  0x10007ff25360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10007ff25370: 00 00 00 00 f1 f1 f1 f1 00 00 00[f2]f2 f2 f2 f2
  0x10007ff25380: 00 00 00 00 00 f2 f2 f2 00 00 00 00 00 00 00 00
  0x10007ff25390: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2
  0x10007ff253a0: f2 f2 f2 f2 00 00 f2 f2 f2 f2 f2 f2 00 00 00 f2
  0x10007ff253b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007ff253c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==11821==ABORTING
```

GDB callstack:
```
Thread 1 "WPEWebProcess" hit Breakpoint 9, __sanitizer::Die () at ../../../../libsanitizer/sanitizer_common/sanitizer_termination.cc:49
49	void NORETURN Die() {
(gdb) bt
#0  0x00007fa59c9be5d0 in __sanitizer::Die() () at ../../../../libsanitizer/sanitizer_common/sanitizer_termination.cc:49
#1  0x00007fa59c9a0ce5 in __asan::ScopedInErrorReport::~ScopedInErrorReport() (this=<optimized out>, __in_chrg=<optimized out>) at ../../../../libsanitizer/asan/asan_report.cc:181
#2  0x00007fa59c9a0ce5 in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) (pc=<optimized out>, bp=bp@entry=140737481438816, sp=sp@entry=140737481438800, addr=addr@entry=140737481448408, is_write=is_write@entry=false, access_size=access_size@entry=8, exp=0, fatal=false) at ../../../../libsanitizer/asan/asan_report.cc:397
#3  0x00007fa59c9a18ab in __asan::__asan_report_load8_noabort(__sanitizer::uptr) (addr=addr@entry=140737481448408) at ../../../../libsanitizer/asan/asan_rtl.cc:112
#4  0x00007fa5963c4dc6 in JSC::ConservativeRoots::genericAddSpan<JSC::CompositeMarkHook>(void*, void*, JSC::CompositeMarkHook&) (this=<optimized out>, begin=<optimized out>, end=0x7fffff97c000, markHook=...) at /usr/include/c++/8/array:189
#5  0x00007fa5963c743e in JSC::ConservativeRoots::add(void*, void*, JSC::JITStubRoutineSet&, JSC::CodeBlockSet&) (this=this@entry=0x7fffff967fb0, begin=<optimized out>, end=<optimized out>, jitStubRoutines=..., codeBlocks=...) at ../Source/JavaScriptCore/heap/ConservativeRoots.cpp:144
#6  0x00007fa591f7ebd1 in JSC::MachineThreads::gatherFromCurrentThread(JSC::ConservativeRoots&, JSC::JITStubRoutineSet&, JSC::CodeBlockSet&, JSC::CurrentThreadState&) (this=this@entry=0x602000005bd0, conservativeRoots=..., jitStubRoutines=..., codeBlocks=..., currentThreadState=...) at ../Source/JavaScriptCore/heap/MachineStackMarker.cpp:51
#7  0x00007fa591f80e21 in JSC::MachineThreads::gatherConservativeRoots(JSC::ConservativeRoots&, JSC::JITStubRoutineSet&, JSC::CodeBlockSet&, JSC::CurrentThreadState*) (this=0x602000005bd0, conservativeRoots=..., jitStubRoutines=..., codeBlocks=..., currentThreadState=<optimized out>) at ../Source/JavaScriptCore/heap/MachineStackMarker.cpp:205
#8  0x00007fa591f0cba6 in JSC::Heap::gatherStackRoots(JSC::ConservativeRoots&) (roots=..., this=<optimized out>) at /usr/include/c++/8/bits/unique_ptr.h:342
#9  0x00007fa591f0cba6 in JSC::Heap::<lambda(JSC::SlotVisitor&, const JSC::VisitingTimeout&)>::operator()(JSC::SlotVisitor &, const JSC::VisitingTimeout &) (slotVisitor=..., __closure=<optimized out>) at ../Source/JavaScriptCore/heap/Heap.cpp:2589
#10 0x00007fa591fbce05 in WTF::Function<void (JSC::SlotVisitor&, JSC::VisitingTimeout const&)>::operator()(JSC::SlotVisitor&, JSC::VisitingTimeout const&) const (in#1=..., in#0=..., this=0x606000012338) at /usr/include/c++/8/bits/unique_ptr.h:342
#11 0x00007fa591fbce05 in JSC::MarkingConstraint::execute(JSC::SlotVisitor&, bool&, WTF::MonotonicTime) (this=<optimized out>, visitor=..., didVisitSomething=@0x7fffff968ba0: false, timeout=...) at ../Source/JavaScriptCore/heap/MarkingConstraint.cpp:71
#12 0x00007fa591fbe77f in JSC::MarkingConstraintSet::ExecutionContext::execute(unsigned long) (index=<optimized out>, this=0x7fffff968b80) at /usr/include/c++/8/bits/unique_ptr.h:342
#13 0x00007fa591fbe77f in JSC::MarkingConstraintSet::ExecutionContext::drain(WTF::BitVector&) (unexecuted=..., this=0x7fffff968b80) at ../Source/JavaScriptCore/heap/MarkingConstraintSet.cpp:58
#14 0x00007fa591fbe77f in JSC::MarkingConstraintSet::executeConvergenceImpl(JSC::SlotVisitor&, WTF::MonotonicTime) (this=this@entry=0x6070000082f0, visitor=..., timeout=...) at ../Source/JavaScriptCore/heap/MarkingConstraintSet.cpp:162
#15 0x00007fa591fc1329 in JSC::MarkingConstraintSet::executeConvergence(JSC::SlotVisitor&, WTF::MonotonicTime) (this=0x6070000082f0, visitor=..., timeout=..., timeout@entry=<error reading variable: Could not find type for DW_OP_const_type>) at ../Source/JavaScriptCore/heap/MarkingConstraintSet.cpp:136
#16 0x00007fa591f588b2 in JSC::Heap::runFixpointPhase(JSC::GCConductor) (this=this@entry=0x62f000000410, conn=conn@entry=JSC::GCConductor::Mutator) at /usr/include/c++/8/bits/unique_ptr.h:342
#17 0x00007fa591f65b4a in JSC::Heap::runCurrentPhase(JSC::GCConductor, JSC::CurrentThreadState*) (currentThreadState=0x7fffff969bc0, conn=JSC::GCConductor::Mutator, this=0x62f000000410) at ../Source/JavaScriptCore/heap/Heap.cpp:1124
#18 0x00007fa591f65b4a in JSC::Heap::runCurrentPhase(JSC::GCConductor, JSC::CurrentThreadState*) (this=0x62f000000410, conn=<optimized out>, currentThreadState=0x7fffff969bc0) at ../Source/JavaScriptCore/heap/Heap.cpp:1096
#19 0x00007fa591f72257 in JSC::Heap::<lambda(JSC::CurrentThreadState&)>::operator() (__closure=0x7fffff969d70, state=...) at ../Source/JavaScriptCore/heap/Heap.cpp:1740
#20 0x00007fa591f72257 in WTF::ScopedLambdaFunctor<void(JSC::CurrentThreadState&), JSC::Heap::collectInMutatorThread()::<lambda(JSC::CurrentThreadState&)> >::implFunction(void *, JSC::CurrentThreadState &) (argument=0x7fffff969d60, arguments#0=...) at ../Source/WTF/wtf/ScopedLambda.h:104
#21 0x00007fa591f8129b in WTF::ScopedLambda<void (JSC::CurrentThreadState&)>::operator()<JSC::CurrentThreadState&>(JSC::CurrentThreadState&) const (this=0x7fffff969d60, this=0x7fffff969d60) at ../Source/WTF/wtf/ScopedLambda.h:54
#22 0x00007fa591f8129b in JSC::callWithCurrentThreadState(WTF::ScopedLambda<void (JSC::CurrentThreadState&)> const&) (lambda=...) at ../Source/JavaScriptCore/heap/MachineStackMarker.cpp:224
#23 0x00007fa591f65f31 in JSC::Heap::collectInMutatorThread() (this=this@entry=0x62f000000410) at /usr/include/c++/8/bits/move.h:74
#24 0x00007fa591f66083 in JSC::Heap::stopIfNecessarySlow(unsigned int) (oldState=<optimized out>, this=0x62f000000410) at ../Source/JavaScriptCore/heap/Heap.cpp:1721
#25 0x00007fa591f66083 in JSC::Heap::stopIfNecessarySlow(unsigned int) (this=0x62f000000410, oldState=<optimized out>) at ../Source/JavaScriptCore/heap/Heap.cpp:1705
#26 0x00007fa591f6940d in JSC::Heap::stopIfNecessarySlow() (this=this@entry=0x62f000000410) at /usr/include/c++/8/bits/atomic_base.h:390
#27 0x00007fa591f6c576 in JSC::Heap::stopIfNecessary() (this=0x62f000000410) at ../Source/JavaScriptCore/heap/HeapInlines.h:269
#28 0x00007fa591f6c576 in JSC::Heap::collectIfNecessaryOrDefer(JSC::GCDeferralContext*) (deferralContext=<optimized out>, this=0x62f000000410) at ../Source/JavaScriptCore/heap/Heap.cpp:2510
#29 0x00007fa591f6c576 in JSC::Heap::collectIfNecessaryOrDefer(JSC::GCDeferralContext*) (this=0x62f000000410, deferralContext=deferralContext@entry=0x0) at ../Source/JavaScriptCore/heap/Heap.cpp:2487
#30 0x00007fa591fe94e0 in JSC::MarkedAllocator::allocateSlowCaseImpl(JSC::GCDeferralContext*, bool) (this=0x6120001666c0, deferralContext=<optimized out>, crashOnFailure=<optimized out>) at ../Source/JavaScriptCore/heap/MarkedAllocator.cpp:203
#31 0x00007fa592024be8 in JSC::MarkedAllocator::allocate(JSC::GCDeferralContext*) (deferralContext=<optimized out>, this=0x6120001666c0) at ../Source/JavaScriptCore/heap/MarkedAllocatorInlines.h:48
#32 0x00007fa592024be8 in JSC::Subspace::allocate(unsigned long) (this=this@entry=0x62f000004a28, size=size@entry=112) at ../Source/JavaScriptCore/heap/Subspace.cpp:100
#33 0x00007fa591d1d44f in JSC::tryAllocateCellHelper<JSC::Structure, (JSC::AllocationFailureMode)0, (JSC::GCDeferralContextArgPresense)1>(JSC::Heap&, JSC::GCDeferralContext*, unsigned long) (size=112, deferralContext=0x0, heap=...) at ../Source/JavaScriptCore/runtime/JSCellInlines.h:138
#34 0x00007fa591d1d44f in JSC::allocateCell<JSC::Structure>(JSC::Heap&, unsigned long) (size=112, heap=...) at ../Source/JavaScriptCore/runtime/JSCellInlines.h:180
#35 0x00007fa591d1d44f in JSC::Structure::create(JSC::VM&, JSC::JSGlobalObject*, JSC::JSValue, JSC::TypeInfo const&, JSC::ClassInfo const*, unsigned char, unsigned int) (inlineCapacity=0, indexingType=0 '\000', classInfo=<optimized out>, typeInfo=..., prototype=..., globalObject=0x62d0001100a0, vm=...) at ../Source/JavaScriptCore/runtime/StructureInlines.h:41
#36 0x00007fa591d1d44f in WebCore::JSMouseEvent::createStructure(JSC::VM&, JSC::JSGlobalObject*, JSC::JSValue) (prototype=..., globalObject=0x62d0001100a0, vm=...) at DerivedSources/WebCore/JSMouseEvent.h:46
#37 0x00007fa591d1d44f in WebCore::getDOMStructure<WebCore::JSMouseEvent>(JSC::VM&, WebCore::JSDOMGlobalObject&) (globalObject=..., vm=...) at ../Source/WebCore/bindings/js/JSDOMWrapperCache.h:86
#38 0x00007fa591d1d44f in WebCore::getDOMStructure<WebCore::JSMouseEvent>(JSC::VM&, WebCore::JSDOMGlobalObject&) (globalObject=..., vm=...) at ../Source/WebCore/bindings/js/JSDOMWrapperCache.h:82
#39 0x00007fa591d1d44f in WebCore::createWrapper<WebCore::MouseEvent, WebCore::MouseEvent>(WebCore::JSDOMGlobalObject*, WTF::Ref<WebCore::MouseEvent>&&) (globalObject=globalObject@entry=0x62d0001100a0, domObject=...) at ../Source/WebCore/bindings/js/JSDOMWrapperCache.h:188
#40 0x00007fa591d2dc1b in WebCore::createWrapper<WebCore::MouseEvent, WebCore::Event>(WebCore::JSDOMGlobalObject*, WTF::Ref<WebCore::Event>&&) (domObject=..., globalObject=0x62d0001100a0) at ../Source/WTF/wtf/Ref.h:220
#41 0x00007fa591d2dc1b in WebCore::toJSNewlyCreated(JSC::ExecState*, WebCore::JSDOMGlobalObject*, WTF::Ref<WebCore::Event>&&) (globalObject=0x62d0001100a0, event=...) at ../Source/WebCore/bindings/js/JSEventCustom.cpp:52
#42 0x00007fa591d39721 in WebCore::wrap<WebCore::Event>(JSC::ExecState*, WebCore::JSDOMGlobalObject*, WebCore::Event&) (domObject=..., globalObject=<optimized out>, state=0x62d0001100e8) at ../Source/WTF/wtf/RefCounted.h:46
#43 0x00007fa591d39721 in WebCore::wrap<WebCore::Event>(JSC::ExecState*, WebCore::JSDOMGlobalObject*, WebCore::Event&) (domObject=..., globalObject=<optimized out>, state=0x62d0001100e8) at ../Source/WebCore/bindings/js/JSDOMWrapperCache.h:198
#44 0x00007fa591d39721 in WebCore::toJS(JSC::ExecState*, WebCore::JSDOMGlobalObject*, WebCore::Event&) (state=state@entry=0x62d0001100e8, globalObject=globalObject@entry=0x62d0001100a0, event=...) at ../Source/WebCore/bindings/js/JSEventCustom.cpp:60
#45 0x00007fa5919b159c in WebCore::toJS(JSC::ExecState*, WebCore::JSDOMGlobalObject*, WebCore::Event*) (impl=0x610000044e40, globalObject=0x62d0001100a0, state=0x62d0001100e8) at DerivedSources/WebCore/JSEvent.h:79
#46 0x00007fa5919b159c in WebCore::JSEventListener::handleEvent(WebCore::ScriptExecutionContext&, WebCore::Event&) (this=0x6040000c1350, scriptExecutionContext=..., event=...) at ../Source/WebCore/bindings/js/JSEventListener.cpp:142
#47 0x00007fa58d13097f in WebCore::EventTarget::fireEventListeners(WebCore::Event&, WTF::Vector<WTF::RefPtr<WebCore::RegisteredEventListener>, 1ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>) (this=this@entry=0x60800005f8a0, event=..., listeners=...) at ../Source/WebCore/dom/RegisteredEventListener.h:51
#48 0x00007fa58d13406b in WebCore::EventTarget::fireEventListeners(WebCore::Event&) (this=0x60800005f8a0, event=...) at ../Source/WebCore/dom/EventTarget.cpp:238
#49 0x00007fa590d1f56c in WebCore::EventContext::handleLocalEvents(WebCore::Event&) const (this=this@entry=0x604000144f50, event=...) at ../Source/WTF/wtf/RefPtr.h:79
#50 0x00007fa590d1fa0d in WebCore::MouseOrFocusEventContext::handleLocalEvents(WebCore::Event&) const (this=0x604000144f50, event=...) at ../Source/WebCore/dom/EventContext.cpp:85
#51 0x00007fa58d11d012 in WebCore::dispatchEventInDOM (path=..., event=...) at /usr/include/c++/8/bits/unique_ptr.h:342
#52 0x00007fa58d11d012 in WebCore::EventDispatcher::dispatchEvent(WebCore::Node&, WebCore::Event&) (node=..., event=...) at ../Source/WebCore/dom/EventDispatcher.cpp:163
#53 0x00007fa58d0b4b77 in WebCore::Element::dispatchMouseEvent(WebCore::PlatformMouseEvent const&, WTF::AtomicString const&, int, WebCore::Element*) (this=0x60800005f8a0, platformEvent=..., eventType=..., detail=detail@entry=1, relatedTarget=relatedTarget@entry=0x0) at ../Source/WebCore/dom/Element.cpp:277
#54 0x00007fa58e4351e9 in WebCore::EventHandler::dispatchMouseEvent(WTF::AtomicString const&, WebCore::Node*, bool, int, WebCore::PlatformMouseEvent const&, bool) (this=this@entry=0x615000009e00, eventType=..., targetNode=0x60700005dbe0, clickCount=<optimized out>, platformMouseEvent=..., setUnder=<optimized out>) at ../Source/WTF/wtf/RefPtr.h:85
#55 0x00007fa58e451d34 in WebCore::EventHandler::handleMouseReleaseEvent(WebCore::PlatformMouseEvent const&) (this=0x615000009e00, platformMouseEvent=...) at /usr/include/c++/8/bits/unique_ptr.h:342
#56 0x00007fa58fcbb5fe in WebCore::UserInputBridge::handleMouseReleaseEvent(WebCore::PlatformMouseEvent const&, WebCore::InputSource) (this=<optimized out>, mouseEvent=...) at /usr/include/c++/8/bits/unique_ptr.h:342
#57 0x00007fa58bd2e03a in WebKit::handleMouseEvent (page=0x61a000009c80, mouseEvent=...) at /usr/include/c++/8/bits/unique_ptr.h:342
#58 0x00007fa58bd2e03a in WebKit::WebPage::mouseEvent(WebKit::WebMouseEvent const&) (this=this@entry=0x61a000009c80, mouseEvent=...) at ../Source/WebKit/WebProcess/WebPage/WebPage.cpp:2388
#59 0x00007fa58c47ed3c in IPC::callMemberFunctionImpl<WebKit::WebPage, void (WebKit::WebPage::*)(WebKit::WebMouseEvent const&), std::tuple<WebKit::WebMouseEvent>, 0ul>(WebKit::WebPage*, void (WebKit::WebPage::*)(WebKit::WebMouseEvent const&), std::tuple<WebKit::WebMouseEvent>&&, std::integer_sequence<unsigned long, 0ul>) (args=..., function=<optimized out>, object=0x61a000009c80) at ../Source/WebKit/Platform/IPC/HandleMessage.h:38
#60 0x00007fa58c47ed3c in IPC::callMemberFunction<WebKit::WebPage, void (WebKit::WebPage::*)(WebKit::WebMouseEvent const&), std::tuple<WebKit::WebMouseEvent>, std::integer_sequence<unsigned long, 0ul> >(std::tuple<WebKit::WebMouseEvent>&&, WebKit::WebPage*, void (WebKit::WebPage::*)(WebKit::WebMouseEvent const&)) (function=<optimized out>, object=0x61a000009c80, args=...) at ../Source/WebKit/Platform/IPC/HandleMessage.h:46
#61 0x00007fa58c47ed3c in IPC::handleMessage<Messages::WebPage::MouseEvent, WebKit::WebPage, void (WebKit::WebPage::*)(WebKit::WebMouseEvent const&)>(IPC::Decoder&, WebKit::WebPage*, void (WebKit::WebPage::*)(WebKit::WebMouseEvent const&)) (function=<optimized out>, object=0x61a000009c80, decoder=...) at ../Source/WebKit/Platform/IPC/HandleMessage.h:126
#62 0x00007fa58c47ed3c in WebKit::WebPage::didReceiveWebPageMessage(IPC::Connection&, IPC::Decoder&) (this=this@entry=0x61a000009c80, connection=..., decoder=...) at DerivedSources/WebKit/WebPageMessageReceiver.cpp:205
#63 0x00007fa58bd554c4 in WebKit::WebPage::didReceiveMessage(IPC::Connection&, IPC::Decoder&) (this=<optimized out>, connection=..., decoder=...) at ../Source/WebKit/WebProcess/WebPage/WebPage.cpp:4207
#64 0x00007fa58b0c670c in IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) (this=this@entry=0x6170000000e8, connection=..., decoder=...) at ../Source/WebKit/Platform/IPC/MessageReceiverMap.cpp:123
#65 0x00007fa58b98f125 in WebKit::WebProcess::didReceiveMessage(IPC::Connection&, IPC::Decoder&) (this=0x617000000080, connection=..., decoder=...) at ../Source/WebKit/Shared/ChildProcess.h:78
#66 0x00007fa58b0b3060 in IPC::Connection::dispatchMessage(IPC::Decoder&) (decoder=..., this=0x614000000c40) at ../Source/WebKit/Platform/IPC/Connection.cpp:901
#67 0x00007fa58b0b3060 in IPC::Connection::dispatchMessage(std::unique_ptr<IPC::Decoder, std::default_delete<IPC::Decoder> >) (this=0x614000000c40, message=std::unique_ptr<IPC::Decoder> = {...}) at ../Source/WebKit/Platform/IPC/Connection.cpp:928
#68 0x00007fa58b0b70b2 in IPC::Connection::dispatchOneMessage() (this=<optimized out>) at /usr/include/c++/8/bits/move.h:74
#69 0x00007fa59b034f10 in WTF::Function<void ()>::operator()() const (this=0x7fffff97afd0) at /usr/include/c++/8/bits/unique_ptr.h:342
#70 0x00007fa59b034f10 in WTF::RunLoop::performWork() (this=0x60c000000700) at ../Source/WTF/wtf/RunLoop.cpp:106
#71 0x00007fa59b12de8c in WTF::RunLoop::<lambda(gpointer)>::operator() (__closure=0x0, userData=<optimized out>) at ../Source/WTF/wtf/glib/RunLoopGLib.cpp:68
#72 0x00007fa59b12de8c in WTF::RunLoop::<lambda(gpointer)>::_FUN(gpointer) () at ../Source/WTF/wtf/glib/RunLoopGLib.cpp:70
#73 0x00007fa58725506d in g_main_dispatch (context=0x60f0000009a0) at gmain.c:3182
#74 0x00007fa58725506d in g_main_context_dispatch (context=context@entry=0x60f0000009a0) at gmain.c:3847
#75 0x00007fa587255438 in g_main_context_iterate (context=0x60f0000009a0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3920
#76 0x00007fa587255762 in g_main_loop_run (loop=0x602000001090) at gmain.c:4116
#77 0x00007fa59b131487 in WTF::RunLoop::run() () at ../Source/WTF/wtf/glib/RunLoopGLib.cpp:96
#78 0x00007fa58c1840df in WebKit::ChildProcessMain<WebKit::WebProcess, WebKit::WebProcessMain>(int, char**) (argc=<optimized out>, argv=<optimized out>) at ../Source/WebKit/Shared/unix/ChildProcessMain.h:41
#79 0x00007fa586d2b413 in __libc_start_main (main=0x400c70 <main(int, char**)>, argc=3, argv=0x7fffff97b638, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffff97b628) at ../csu/libc-start.c:308
#80 0x0000000000400d7e in _start ()
```

**Comment by calvaris** [comment]
This version is unsupported now.
