### ISSUE TITLE
[wpe-2.28] random crashes in Inspector::InjectedScriptModule::ensureInjected

### ISSUE THREAD

**Issue by emutavchi** [Metrological/WebKitForWayland#839]
This happens randomly while inspecting PlutoTV.

```
2022 Apr 27 17:42:04.483208 WPEFramework[29228]:  Error when calling 'injectModule' for 'CommandLineAPI': SecurityError: Blocked a frame with origin "null" from accessing a cross-origin frame. Protocols, domains, and ports must match. (26:79)
2022 Apr 27 17:42:04.483938 WPEFramework[29228]:  //# sourceURL=__InjectedScript_CommandLineAPIModuleSource.js
```

callstack of crashed thread:
```
Core was generated by `/usr/libexec/wpe-webkit-1.0/WPEWebProcess 7 18'.                              
Program terminated with signal SIGABRT, Aborted.                                                     
#0  __libc_do_syscall () at libc-do-syscall.S:49                                                     
49      libc-do-syscall.S: No such file or directory.             
[Current thread is 1 (Thread 0xaf100500 (LWP 31109))]                                                
(gdb) bt                                                                                                                                                                                                   
#0  __libc_do_syscall () at libc-do-syscall.S:49                                                                                                                                                           
#1  0xb1dfedb4 in __libc_signal_restore_set (set=...) at ../sysdeps/unix/sysv/linux/internal-signals.h:86
#2  __GI_raise (sig=...) at ../sysdeps/unix/sysv/linux/raise.c:48                                    
#3  0xb1df26dc in __GI_abort () at abort.c:79                                                        
#4  0xb344954e in CRASH_WITH_INFO(...) () at DerivedSources/ForwardingHeaders/wtf/Assertions.h:740   
#5  Inspector::InjectedScriptModule::ensureInjected () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/JavaScriptCore/inspector/InjectedScriptModule.cpp:97                          
#6  0xb2ba145a in WebCore::CommandLineAPIModule::injectIfNeeded () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WebCore/inspector/CommandLineAPIModule.cpp:43                     #7  0xb34146f2 in Inspector::InjectedScriptManager::injectedScriptFor () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/JavaScriptCore/inspector/InjectedScriptManager.cpp:212
#8  0xb345a6d2 in Inspector::InspectorHeapAgent::getRemoteObject () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/JavaScriptCore/inspector/agents/InspectorHeapAgent.cpp:250       
#9  0xb342f0a2 in Inspector::HeapBackendDispatcher::getRemoteObject () at DerivedSources/JavaScriptCore/inspector/InspectorBackendDispatchers.cpp:4276                                                     #10 0xb341c2c2 in Inspector::HeapBackendDispatcher::dispatch () at DerivedSources/JavaScriptCore/inspector/InspectorBackendDispatchers.cpp:4097            
#11 0xb34439a8 in Inspector::BackendDispatcher::dispatch () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/JavaScriptCore/inspector/InspectorBackendDispatcher.cpp:180              #12 0xb2221718 in IPC::callMemberFunctionImpl<WebKit::WebPage, void (WebKit::WebPage::*)(WTF::String const&, WTF::String const&), std::tuple<WTF::String, WTF::String>, 0u, 1u> () at /usr/src/debug/wpe-we
bkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WebKit/Platform/IPC/HandleMessage.h:41                                                                                                                       
#13 IPC::callMemberFunction<WebKit::WebPage, void (WebKit::WebPage::*)(WTF::String const&, WTF::String const&), std::tuple<WTF::String, WTF::String>, std::integer_sequence<unsigned int, 0u, 1u> > () at /
usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WebKit/Platform/IPC/HandleMessage.h:47                                                                                                   
#14 IPC::handleMessage<Messages::WebPage::SendMessageToTargetBackend, WebKit::WebPage, void (WebKit::WebPage::*)(WTF::String const&, WTF::String const&)> () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+6
3ebf8309e-r0/git/Source/WebKit/Platform/IPC/HandleMessage.h:120                                      
#15 WebKit::WebPage::didReceiveWebPageMessage () at DerivedSources/WebKit/WebPageMessageReceiver.cpp:1174
#16 0xb2293eec in IPC::MessageReceiverMap::dispatchMessage () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WebKit/Platform/IPC/MessageReceiverMap.cpp:123
#17 0xb23a472a in WebKit::WebProcess::didReceiveMessage () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WebKit/WebProcess/WebProcess.cpp:746                                      
#18 0xb228f028 in IPC::Connection::dispatchMessage () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WebKit/Platform/IPC/Connection.cpp:1008                                        
#19 0xb2291cb2 in IPC::Connection::dispatchMessage () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WebKit/Platform/IPC/Connection.cpp:1077
#20 0xb2292258 in IPC::Connection::dispatchOneIncomingMessage () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WebKit/Platform/IPC/Connection.cpp:1146
#21 0xb37e5104 in WTF::Function<void ()>::operator()() const () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WTF/wtf/Function.h:84
#22 WTF::RunLoop::performWork () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WTF/wtf/RunLoop.cpp:107
#23 0xb38162e6 in operator() () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:68
#24 _FUN () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:70
#25 0xb0d29864 in g_main_dispatch (context=...) at ../glib-2.62.4/glib/gmain.c:3216
#26 g_main_context_dispatch (context=...) at ../glib-2.62.4/glib/gmain.c:3885
#27 0xb0d299ce in g_main_context_iterate (context=..., block=..., dispatch=..., self=...) at ../glib-2.62.4/glib/gmain.c:3958
#28 0xb0d29d08 in g_main_loop_run (loop=...) at ../glib-2.62.4/glib/gmain.c:4152
#29 0xb3816a3c in WTF::RunLoop::run () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:96
#30 0xb240423e in WebKit::AuxiliaryProcessMain<WebKit::WebProcess, WebKit::WebProcessMainWPE> () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+63ebf8309e-r0/git/Source/WebKit/Shared/AuxiliaryProcessMain.h
:68
#31 0xb1df298e in __libc_start_main (main=..., argc=..., argv=..., init=..., fini=..., rtld_fini=..., stack_end=...) at libc-start.c:308
#32 0x00010600 in _start () at ../sysdeps/arm/start.S:126
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by magomez** [comment]
This happens with the new inspector, doesn't it?

**Comment by emutavchi** [comment]
@magomez I can double-check, but I believe inspector was enabled via WEBKIT_INSPECTOR_SERVER in this case.

**Comment by emutavchi** [comment]
@magomez it was via WEBKIT_INSPECTOR_SERVER, here is env variable from the core file:

```
(gdb) p __environ[70]
$64 = 0xbbf47e30 "WEBKIT_INSPECTOR_SERVER=10.0.0.26:10001"
```

**Comment by magomez** [comment]
> @magomez it was via WEBKIT_INSPECTOR_SERVER, here is env variable from the core file:

Ok, so the inspector that needs to be run inside a wkgtk browser.

Do you have an URL to test this? The normal pluto tv URL doesn't seem very STB friendly, is there an alternative?

**Comment by magomez** [comment]
@emutavchi , were you able to get some logs of the crash with the patch I sent you?

**Comment by magomez** [comment]
I've been told that this is not happening anymore and that it can be closed. Please feel free to reopen if needed.
